### ISSUE TITLE
Use `const`/`let`

### ISSUE THREAD

**Issue by luketlancaster** [nswalters/sorting-hat#11]
There's places where you're creating variables but not using the `const` or `let` keywords to create them (see https://github.com/nswalters/sorting-hat/blob/master/js/students.js#L2 for example). JS lets you this because JS lets you do almost anything you want, but it's not good practice because it allows variables to leak outside of the scope they're defined in. So if you create a new variable `student` inside a function but don't use `let` or `const`, I can come along and change the value of that variable outside of the function which can lead to sadness/tears/unexpected behavior. Not a huge deal, but best practice to be as safe as possible with your variable definitions

**Comment by nswalters** [comment]
Thanks for the heads up!  That's my Python side coming out... 😄

Current definitions should be good now and will definitely keep this in mind for the future! 👍

**Comment by nswalters** [comment]
#
